# Generated by Django 5.0.3 on 2024-05-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room_id', 'check_in_date', 'check_out_date')},
        ),
    ]
